name: .NET

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  ProjectName: PowerCycler

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          targetPlatform: linux-arm
        - os: ubuntu-latest
          targetPlatform: linux-x64
        - os: windows-latest
          targetPlatform: win-x64
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Clone
      uses: actions/checkout@v3
    
    - name: Restore
      run: dotnet restore --runtime ${{ matrix.targetPlatform }} --locked-mode --verbosity normal

    - name: Build
      run: dotnet build ${{ env.ProjectName }} --no-restore --runtime ${{ matrix.targetPlatform }} --configuration Release --no-self-contained --verbosity normal

    - name: Publish
      run: dotnet publish --no-build --configuration Release -p:PublishSingleFile=true --runtime ${{ matrix.targetPlatform }} --no-self-contained
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}-${{ env.TargetPlatform }}
        path: |
          ${{ env.ProjectName }}/bin/Release/net7.0/${{ matrix.targetPlatform }}/publish/${{ env.ProjectName }}
          ${{ env.ProjectName }}/bin/Release/net7.0/${{ matrix.targetPlatform }}/publish/${{ env.ProjectName }}.exe
          ${{ env.ProjectName }}/bin/Release/net7.0/${{ matrix.targetPlatform }}/publish/appsettings.json
        if-no-files-found: error
